esphome:
  name: plant-bridge-1
  comment: ESP WROOM 32

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "8pV+BNSUJ5Ks0Flv3wbBS6ktzqClqmvnkDsReHXn4Gc="

ota:
  password: "1c16f03ced87f64d4a762a272795d03e"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

prometheus:

web_server:
  port: 80

switch:
  - platform: restart
    name: restart

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: America/Chicago

esp32_ble_tracker:

sensor:
  - platform: wifi_signal
    name: wifi signal
    update_interval: 120s

  - platform: ble_rssi
    mac_address: C4:7C:8D:6B:93:81
    name: "Bitsy rssi"

  - platform: ble_rssi
    mac_address: C4:7C:8D:6B:91:9A
    name: "Abel rssi"

  - platform: ble_rssi
    mac_address: C4:7C:8D:6B:91:99
    name: "Carl rssi"

