substitutions:
  me: "bessy-b"
  meid: "bessy-b"

esphome:
  name: ${me}
  friendly_name: ${me}
  comment: esp32-relay4

esp32:
  variant: esp32
  framework:
    type: esp-idf

logger:

api:
  encryption:
    key: !secret esp_api_key

ota:
  - platform: esphome
    password: !secret esp_ota_pw
    id: my_ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: bessy-b Fallback Hotspot
    password: "n84gt5ei4aAb"

captive_portal:

web_server:
  port: 80
  version: 3

prometheus:
