# Hardware is olimex esp32 poe
# https://www.olimex.com/Products/IoT/ESP32/ESP32-POE/open-source-hardware
# TPS2375PW chip provides ethernet
substitutions:
  me: ble-poe-gw2

esphome:
  name: ${me}
  comment: olimex esp32 poe

esp32:
  board: esp32-poe
  framework:
    type: esp-idf

logger:
  level: info

api:
  encryption:
    key: !secret esp_api_key

ota:
  password: !secret esp_ota_pw
  id: my_ota

web_server:
  port: 80

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12

time:
  - platform: homeassistant
    timezone: America/Chicago

text_sensor:
  - platform: version
    name: ${me} ESPHome Version

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

sensor:
  - platform: uptime
    name: ${me} uptime
    update_interval: 120s

button:
  - platform: safe_mode
    name: ${me} safe mode boot
    entity_category: diagnostic