# Hardware is olimex esp32 poe
# https://www.olimex.com/Products/IoT/ESP32/ESP32-POE/open-source-hardware
# TPS2375PW chip provides ethernet

esphome:
  name: ble-poe-gw2
  friendly_name: ble-poe-gw2
  comment: olimex esp32 poe

esp32:
  board: esp32-poe
  framework:
    type: esp-idf

logger:
  level: info

api:
  encryption:
    key: "7JW1DLwPqhA/XcQhLu21FMTifE1sPY7nKEUyLocajNY="

ota:
  password: "6796c660ba1ce3074cfb8cbe88aebd83"

web_server:
  port: 80

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: America/Chicago

text_sensor:
  - platform: version
    name: "ESPHome Version"

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

sensor:
  - platform: uptime
    name: uptime
    update_interval: 120s

button:
  - platform: safe_mode
    name: Safe Mode Boot
    entity_category: diagnostic