# hardware is an olimex esp32-gateway
# https://www.olimex.com/Products/IoT/ESP32/ESP32-GATEWAY/open-source-hardware

substitutions:
  me: ble-poe-gw0

esphome:
  name: ${me}
  comment: olimex esp32-gateway 

esp32:
  board: esp32-gateway
  framework:
    type: esp-idf

logger:
  level: info

api:
  encryption:
    key: !secret esp_api_key

ota:
  - platform: esphome
    password: !secret esp_ota_pw
    id: my_ota

web_server:
  port: 80

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0

time:
  - platform: homeassistant
    timezone: America/Chicago

text_sensor:
  - platform: version
    name: ${me} ESPHome Version

switch:
  - platform: restart
    name: ${me} restart

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

sensor:
  - platform: uptime
    name: ${me} uptime
    update_interval: 120s

button:
- platform: safe_mode
  name: Safe Mode Boot
  entity_category: diagnostic