# This is for a sonoff IW101 1 gang wall switch
# on breaker 4A
substitutions:
  me: boys-bath-light
  on_time: 2700s

esphome:
  name: ${me}
  comment: Sonoff IW101
  on_boot:
    priority: 200
    then:
      - output.turn_on: green_led
      - output.turn_off: red_led

esp8266:
  board: esp01_1m
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: info

prometheus:

web_server:
  port: 80

api:
  encryption:
    key: !secret esp_api_key

ota:
  password: !secret esp_ota_pw
  id: my_ota

time:
  - platform: homeassistant
    timezone: America/Chicago

text_sensor:
  - platform: version
    name: ${me} ESPHome Version

switch:
  - platform: restart
    name: ${me} restart

sensor:
  - platform: uptime
    name: ${me} uptime
    update_interval: 120s
    
  - platform: wifi_signal
    name: ${me} wifi signal
    update_interval: 120s

output:
  - platform: gpio
    id: red_led
    pin: GPIO16
    inverted: True
    
  - platform: gpio
    id: green_led
    pin: GPIO2
    inverted: True

  - platform: gpio
    id: relay
    pin: GPIO14

light:
  - platform: binary
    name: Boys Bath Light
    id: my_light
    output: relay
    on_turn_on:
      - output.turn_off: green_led
    on_turn_off:
      - output.turn_on: green_led
      - output.turn_off: red_led

script:
  - id: inching
    then:
      - light.turn_on: my_light
      - delay: ${on_time}
      - light.turn_off: my_light

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: button
    on_press:
      - if:
          condition:
            light.is_on: my_light
          then:
            - script.stop: inching
            - light.turn_off: my_light
          else:
            - script.execute: inching
    on_click:
      - min_length: 2000ms
        max_length: 4000ms
        then:
          if:
            condition:
              script.is_running: inching
            then:
              - script.stop: inching
              - light.turn_on: my_light
              - output.turn_off: green_led
              - output.turn_on: red_led
