# This is for a treatlife SS01S  
substitutions:
  me: boys-bath-vanity-light
  on_time: 600s

esphome:
  name: ${me}
  comment: Treatlife SS01S
  on_boot:
    priority: 200
    then:
      - output.turn_on: white_led
      - output.turn_off: red_led

esp8266:
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: info

prometheus:

web_server:
  port: 80

api:
  encryption:
    key: !secret esp_api_key

ota:
  - platform: esphome
    password: !secret esp_ota_pw
    id: my_ota

time:
  - platform: homeassistant
    timezone: America/Chicago

text_sensor:
  - platform: version
    name: ${me} ESPHome Version

switch:
  - platform: restart
    name: ${me} restart

sensor:
  - platform: uptime
    name:  ${me} uptime
    update_interval: 120s
    
  - platform: wifi_signal
    name:  ${me} uptimwifi signal
    update_interval: 120s

output:
  - platform: gpio
    id: white_led
    pin: GPIO4
    inverted: True
    
  - platform: gpio
    id: red_led
    pin: GPIO5
    inverted: True

  - platform: gpio
    id: relay
    pin: GPIO12

light:
  - platform: binary
    name: Boys Bath Vanity Light
    id: my_light
    output: relay
    on_turn_on:
      - output.turn_off: white_led
    on_turn_off:
      - output.turn_on: white_led
      - output.turn_off: red_led
  
script:
  - id: inching
    then:
      - light.turn_on: my_light
      - delay: ${on_time}
      - light.turn_off: my_light

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    id: button
    on_press:
      - if:
          condition:
            light.is_on: my_light
          then:
            - script.stop: inching
            - light.turn_off: my_light
          else:
            - script.execute: inching
    on_click:
      - min_length: 500ms
        max_length: 2000ms
        then:
          if:
            condition:
              script.is_running: inching
            then:
              - script.stop: inching
              - light.turn_on: my_light
              - output.turn_off: white_led
              - output.turn_on: red_led
