# This is for a sonoff IW101 1 gang wall switch
# on breaker 4A
substitutions:
  name: "boys-bath-light"
  me: "boys_bath_light"
  on_time: 2700s

esphome:
  name: ${name}
  platform: ESP8266
  board: esp01_1m
  on_boot:
    priority: 200
    then:
      - output.turn_on: green_led
      - output.turn_off: red_led
  comment: "Sonoff IW101"
  
wifi:
  ssid: !secret ssid2
  password: !secret password2

logger:

prometheus:

web_server:
  port: 80

api:

ota:

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: America/Chicago


switch:
  - platform: restart
    name: "${name} restart"


text_sensor:
  - platform: version
    name: "ESPHome Version"


output:
  - platform: gpio
    id: red_led
    pin: GPIO16
    inverted: True
    
  - platform: gpio
    id: green_led
    pin: GPIO2
    inverted: True

  - platform: gpio
    id: relay
    pin: GPIO14


light:
  - platform: binary
    name: "Boys Bath Light"
    id: ${me}
    output: relay
    on_turn_on:
      - output.turn_off: green_led
    on_turn_off:
      - output.turn_on: green_led
      - output.turn_off: red_led


script:
  - id: inching
    then:
      - light.turn_on: ${me}
      - delay: ${on_time}
      - light.turn_off: ${me}


sensor:
  - platform: uptime
    name: ${name} uptime
    update_interval: 120s
    
  - platform: wifi_signal
    name: ${name} wifi signal
    update_interval: 120s


binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${name} button"
    on_press:
      - if:
          condition:
            light.is_on: ${me}
          then:
            - script.stop: inching
            - light.turn_off: ${me}
          else:
            - script.execute: inching
    on_click:
      - min_length: 2000ms
        max_length: 4000ms
        then:
          if:
            condition:
              script.is_running: inching
            then:
              - script.stop: inching
              - light.turn_on: ${me}
              - output.turn_off: green_led
              - output.turn_on: red_led
