substitutions:
  name: "christmas-tree"

esphome:
  name: ${name}
  comment: "Sonoff basic"

esp8266:
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

prometheus:

web_server:
  port: 80

logger:
  level: info

api:
  encryption:
    key: !secret esp_api_key

ota:
  - platform: esphome
    password: !secret esp_ota_pw
    id: my_ota

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: America/Chicago


text_sensor:
  - platform: version
    name: "ESPHome Version"

switch:
  - platform: restart
    name: "${name} restart"


sensor:
  - platform: uptime
    name: ${name} uptime
    update_interval: 120s
    
  - platform: wifi_signal
    name: ${name} wifi signal
    update_interval: 120s


binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${name} button"
    on_press:
      - light.toggle: my_light


light:
  - platform: binary
    name: "Christmas Tree"
    id: my_light
    output: relay


output:
  - platform: gpio
    pin: GPIO12
    id: relay

  
status_led:
  pin: GPIO13

