# https://learn.adafruit.com/esp32-s3-reverse-tft-feather/pinouts


substitutions:
  me: current-logger

esphome:
  name: ${me}
  comment: adafruit esp32-s3-reverse-tft-feather
  on_boot: 
    then:
      - output.turn_on: tfti2c_pwr

esp32:
  board: adafruit_feather_esp32s3_tft
  framework:
    type: arduino
    
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: info

api:
  encryption:
    key: !secret esp_api_key

ota:
  - platform: esphome
    password: !secret esp_ota_pw

prometheus:

web_server:
  version: 3

time:
  - platform: homeassistant
    timezone: America/Chicago

text_sensor:
  - platform: version
    name: ${me} ESPHome Version

switch:
  - platform: restart
    name: ${me} restart

i2c:
  sda: GPIO3
  scl: GPIO4

spi:
  clk_pin: GPIO36
  mosi_pin: GPIO35
  miso_pin: GPIO37

output:
  - platform: gpio
    pin: GPIO7
    id: tfti2c_pwr
  
  - platform: gpio
    pin: GPIO13
    id: led


sensor:
  - platform: uptime
    name: ${me} uptime
    update_interval: 120s

  - platform: wifi_signal
    name: ${me} wifi signal
    update_interval: 5s

  - platform: ina2xx_i2c
    address: 0x40
    model: INA228
    shunt_resistance: 0.015 ohm
    max_current: 10A
    update_interval: 100ms
    current:
      name: ${me} current
      id: ina_current
      accuracy_decimals: 5
      filters:
        - throttle: 1s
    power:
      name: ${me} power
      id: ina_power
      filters:
        - throttle: 1s
    bus_voltage:
      name: ${me} bus voltage
      accuracy_decimals: 4
      filters:
        - throttle: 1s
    shunt_voltage:
      name: ${me} shunt voltage
      accuracy_decimals: 6
      filters:
        - throttle: 1s
    energy: 
      name: ${me} energy
      accuracy_decimals: 6
      filters:
        - throttle: 1s
    charge: 
      name: ${me} charge
      accuracy_decimals: 8
      filters:
        - throttle:  1s
    temperature: 
      name: ${me} ina temperature
      accuracy_decimals: 2
      filters:
        - throttle: 1s

  - platform: template
    name: ${me} avg current
    lambda: "return id(ina_current).raw_state;"
    update_interval: 100ms
    accuracy_decimals: 5
    filters:
      - sliding_window_moving_average:
          window_size: 100
          send_every: 10

  - platform: template
    name: ${me} max current
    unit_of_measurement: A
    lambda: "return id(ina_current).raw_state;"
    update_interval: 100ms
    accuracy_decimals: 5
    filters:
      - max:
         window_size: 100
         send_every: 10

  - platform: template
    name: ${me} min current
    unit_of_measurement: A
    lambda: "return id(ina_current).raw_state;"
    update_interval: 100ms
    accuracy_decimals: 5
    filters:
      - min:
         window_size: 100
         send_every: 10

  - platform: max17043
    address: 0x36
    battery_voltage:
      name: ${me} battery boltage
    battery_level:
      name: ${me} battery

display:
  - platform: st7789v
    model: TTGO_TDISPLAY_135X240
    backlight_pin: GPIO45
    dc_pin: GPIO40
    reset_pin: GPIO41
    cs_pin: GPIO42
    show_test_card: true
