substitutions:
  me: current-logger

esphome:
  name: ${me}
  comment: seeed esp32s3

esp32:
  board: seeed_xiao_esp32s3
    
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: info

api:
  encryption:
    key: !secret esp_api_key

ota:
  - platform: esphome
    password: !secret esp_ota_pw

prometheus:

web_server:
  version: 3

time:
  - platform: homeassistant
    timezone: America/Chicago

text_sensor:
  - platform: version
    name: ${me} ESPHome Version

switch:
  - platform: restart
    name: ${me} restart

i2c:
  sda: GPIO5
  scl: GPIO6

sensor:
  - platform: uptime
    name: ${me} uptime
    update_interval: 120s

  - platform: wifi_signal
    name: ${me} wifi signal
    update_interval: 5s

  - platform: ina226
    address: 0x40
    shunt_resistance: 1 ohm
    max_current: .32A
    update_interval: 100ms
    adc_time: 1100us
    adc_averaging: 16
    current:
      name: ${me} current
      id: ina_current
      accuracy_decimals: 5
      filters:
        - throttle: 1s
    power:
      name: ${me} power
      id: ina_power
      filters:
        - throttle: 1s
    bus_voltage:
      name: ${me} bus voltage
      accuracy_decimals: 4
      filters:
        - throttle: 1s
    shunt_voltage:
      name: ${me} shunt voltage
      accuracy_decimals: 6
      filters:
        - throttle: 1s

  - platform: template
    name: ${me} avg current
    lambda: "return id(ina_current).raw_state;"
    update_interval: 100ms
    accuracy_decimals: 5
    filters:
      - sliding_window_moving_average:
          window_size: 100
          send_every: 10

  - platform: template
    name: ${me} max current
    unit_of_measurement: A
    lambda: "return id(ina_current).raw_state;"
    update_interval: 100ms
    accuracy_decimals: 5
    filters:
      - max:
         window_size: 100
         send_every: 10

  - platform: template
    name: ${me} min current
    unit_of_measurement: A
    lambda: "return id(ina_current).raw_state;"
    update_interval: 100ms
    accuracy_decimals: 5
    filters:
      - min:
         window_size: 100
         send_every: 10
