substitutions:
  me: deck-lights
  
esphome:
  name: ${me}
  comment: H801

esp8266:
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.2.160

prometheus:

web_server:
  port: 80

logger:
  level: info

api:
  encryption:
    key: !secret esp_api_key

ota:
  - platform: esphome
    password: !secret esp_ota_pw
    id: my_ota

time:
  - platform: homeassistant
    timezone: America/Chicago

text_sensor:
  - platform: version
    name: ${me} ESPHome Version

switch:
  - platform: restart
    name: ${me} restart

sensor:
  - platform: uptime
    name: ${me} uptime
    update_interval: 120s
    
  - platform: wifi_signal
    name: ${me} wifi signal
    update_interval: 120s

output:
  - platform: esp8266_pwm
    pin: GPIO4
    frequency: 1000 Hz
    id: pwm_w2
    
  - platform: esp8266_pwm
    pin: GPIO12
    frequency: 1000 Hz
    id: pwm_b

  - platform: esp8266_pwm
    pin: GPIO13
    frequency: 1000 Hz
    id: pwm_g

  - platform: esp8266_pwm
    pin: GPIO14
    frequency: 1000 Hz
    id: pwm_w1

  - platform: esp8266_pwm
    pin: GPIO15
    frequency: 1000 Hz
    id: pwm_r

light:
  - platform: monochromatic
    name: Lower Steps Lights
    output: pwm_r

  - platform: monochromatic
    name: Upper Steps Lights
    output: pwm_g

  - platform: monochromatic
    name: Entry Step Lights
    output: pwm_b

  - platform: monochromatic
    name: Porch Steps Lights
    output: pwm_w1
