substitutions:
  name: "driveway-flood"

esphome:
  name: ${name}
  friendly_name: "Driveway Flood"
  comment: "Sonoff basic"

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "weDcHH6uppTGit35hFwUuHDRQad9+vdhFA6Eyu+6848="

ota:
  password: "777c121f2ed0ff16f3b6c88e00fc5700"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

prometheus:

web_server:
  port: 80

text_sensor:
  - platform: version
    name: ESPHome Version

switch:
  - platform: restart
    name: Restart

sensor:
  - platform: uptime
    name: Uptime
    update_interval: 120s
    
  - platform: wifi_signal
    name: wifi signal
    update_interval: 120s

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: Button
    on_press:
      - light.toggle: my_light

light:
  - platform: binary
    name: Light
    id: my_light
    output: relay

output:
  - platform: gpio
    pin: GPIO12
    id: relay
  
status_led:
  pin: GPIO13
