substitutions:
  me: "esp32c6"

esphome:
  name: ${me}
  comment: sparkfun esp32c3

esp32:
  board: sparkfun_esp32c6_thing_plus
  framework:
    type: esp-idf

external_components:
  - source: github://burundiocibu/c6_adc

logger:
  level: INFO

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: false
  reboot_timeout: 60s
  id: wifi_id
  manual_ip: 
    static_ip: 192.168.2.197
    gateway: 192.168.2.1
    subnet: 255.255.255.0
    dns1: 192.168.2.1

ota:
  - platform: esphome
    password: !secret esp_ota_pw
    id: my_ota

api:
  encryption:
    key: !secret esp_api_key

web_server:
  version: 3

# color  signal  abp2   ds18b20  esp32c6
# Red    +3.3     2      1        3V3
# Black  gnd      1      3        GND
# Yellow sda      5               IO3
# Green  scl      6               IO4
# Orange 1wire           2        IO2
#

i2c:
  sda: GPIO3
  scl: GPIO4

one_wire:
  - platform: gpio
    pin: GPIO2

sensor:
  - platform: internal_temperature
    name: ${me} internal temperature
    id: temp
    update_interval: 250ms
    unit_of_measurement: °C
    filters:
      - sliding_window_moving_average:
          window_size: 10
          send_every: 10
          send_first_at: 10

  - platform: c6_adc
    pin: GPIO1
    name: ${me} vbat
    id: vbat
    attenuation: 12db # full scale is 2.450V
    accuracy_decimals: 2
    update_interval: 250ms
    filters:
      - multiply: 2
      - sliding_window_moving_average:
          window_size: 10
          send_every: 10
          send_first_at: 10

  - platform: dallas_temp
    name: t1
    address: 0xe9011877b40fff28
    update_interval: 10s

  - platform: honeywellabp2_i2c
    # ABP2DRRT060MD2A3XX
    address: 0x28
    update_interval: 200ms
    pressure:
      name: pressure
      id: p
      min_pressure: -60
      max_pressure: 60
      transfer_function: "A"
      unit_of_measurement: mBar
      accuracy_decimals: 4
      filters: 
        - offset: -0.4362
        - median:
            window_size: 25
            send_every: 25
            send_first_at: 5

  - platform: template
    lambda: "return id(p).state;"
    name: level
    update_interval: 10s
    unit_of_measurement: cm
    accuracy_decimals: 2
    filters:
      - multiply: 1.0197 # by the book mBar->cmH20
