#!/bin/bash

IFS='.'; fa=($2); unset IFS;
dn=${fa[0]}
ext=${fa[1]}

if [ "$ext" != "yaml" ]; then
    echo must run on a esphome yaml file
    exit 0
fi

# run --it 
echo all:@$ other: $dn $ext
echo docker run --privileged --name esphome-cli -v $PWD/:/config ghcr.io/esphome/esphome run $2 --device $dn
docker run --privileged --name esphome-cli -v $PWD/:/config ghcr.io/esphome/esphome run $2 --device $dn
docker rm esphome-cli