# hardware wemos d1-mini with AM2301 on D2
substitutions:
  name: garage-monitor

esphome:
  name: ${name}
  platform: ESP8266
  board: d1_mini
  comment: "wemos d1"


wifi:
  ssid: !secret ssid2
  password: !secret password2

logger:

api:

ota:

prometheus:

web_server:
  port: 80

time:
  - platform: sntp
    id: sntp_time
    timezone: America/Chicago


text_sensor:
  - platform: version
    name: "ESPHome Version"


switch:
  - platform: restart
    name: ${name} restart


sensor:  
  - platform: uptime
    name: ${name} uptime
    update_interval: 120s
    
  - platform: wifi_signal
    name: ${name} wifi signal
    update_interval: 120s

  - platform: dht
    pin: D2
    temperature:
      name: "Garage Temperature"
    humidity:
      name: "Garage Humidity"
    update_interval: 15s
