# hardware wemos d1-mini with AM2301 on D2
substitutions:
  me: garage-monitor
  
esphome:
  name: ${me}
  comment: wemos d1

esp8266:
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: info

api:
  encryption:
    key: !secret esp_api_key

ota:
  - platform: esphome
    password: !secret esp_ota_pw
    id: my_ota

prometheus:

web_server:
  port: 80

time:
  - platform: homeassistant
    timezone: America/Chicago

text_sensor:
  - platform: version
    name: ${me}ESPHome Version

switch:
  - platform: restart
    name: ${me} restart

sensor:  
  - platform: uptime
    name: ${me} uptime
    update_interval: 120s
    
  - platform: wifi_signal
    name: ${me} wifi signal
    update_interval: 120s

  - platform: dht
    pin: D2
    temperature:
      name: Garage Temperature
    humidity:
      name: Garage Humidity
    update_interval: 15s
