# J1 pin assignments
# 1 gnd
# 2 +24 VDC

# J1 pin assignments & wroom gpio assignments               
# 1 gnd
# 2 5VDC
# 3 relay 1, gpio15
# 4 flow meter 1, gpio13
# 5 relay 2, gpio2
# 6 flow meter 3, gpio14
# 7 relay 3, gpio4
# 8 flow meter 2, gpio12
# 9 relay 4, gpio16
# 10 flow meter 4, gpio27


substitutions:
  me: garden-water

esphome:
  name: ${me}
  comment: esp32 devkit

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: info

api:
  encryption:
    key: !secret esp_api_key

ota:
  - platform: esphome
    password: !secret esp_ota_pw
    id: my_ota

prometheus:

web_server:
  port: 80

text_sensor:
  - platform: version
    name: ${me} ESPHome Version

switch:
  - platform: restart
    name: ${me} restart

  - platform: gpio
    # olla system
    name: ${me} valve 1
    icon: "mdi:valve"
    pin:
      number: 15
      inverted: yes
    
  - platform: gpio
    # SE raised bed
    name: ${me} valve 2
    icon: "mdi:valve"
    pin:
      number: 2
      inverted: yes

  - platform: gpio
    # SW raised bed 
    name: ${me} valve 3
    icon: "mdi:valve"
    pin:
      number: 4
      inverted: yes

  - platform: gpio
    # S raised bed
    name: ${me} valve 4
    icon: "mdi:valve"
    pin:
      number: 16
      inverted: yes

sensor:
  - platform: uptime
    name: ${me} uptime
    update_interval: 120s
    
  - platform: wifi_signal
    name: ${me} wifi signal
    update_interval: 120s

  - platform: pulse_counter
    pin: 13
    name: ${me} flow rate 1
    unit_of_measurement: 'gal/min'
    update_interval: 5s
    accuracy_decimals: 2
    filters:
      # 1928 pulses = 127 oz
      - multiply: 0.000631 
    total:
      name: ${me} usage 1
      accuracy_decimals: 2
      filters: 
        - multiply: 0.000631
      unit_of_measurement: 'gal'

  - platform: pulse_counter
    pin: 26 # was 12; bad idea
    name: ${me} flow rate 2
    unit_of_measurement: 'gal/min'
    update_interval: 5s
    accuracy_decimals: 2
    filters:
      # 1928 pulses = 127 oz
      - multiply: 0.000631 
    total:
      name: ${me} usage 2
      accuracy_decimals: 2
      filters: 
        - multiply: 0.000631
      unit_of_measurement: 'gal'

  - platform: pulse_counter
    pin: 14
    name: ${me} flow rate 3
    unit_of_measurement: 'gal/min'
    update_interval: 5s
    accuracy_decimals: 2
    filters:
      # 1928 pulses = 127 oz
      - multiply: 0.000631 
    total:
      name: ${me} usage 3
      accuracy_decimals: 2
      filters: 
        - multiply: 0.000631
      unit_of_measurement: 'gal'

  - platform: pulse_counter
    pin: 27
    name: ${me} flow rate 4
    unit_of_measurement: 'gal/min'
    update_interval: 5s
    accuracy_decimals: 2
    filters:
      # 1928 pulses = 127 oz
      - multiply: 0.000631 
    total:
      name: ${me} usage 4
      accuracy_decimals: 2
      filters: 
        - multiply: 0.000631
      unit_of_measurement: 'gal'
