#esp32 wroom pin assignments
#13: Rm1 - flow meter 1
#12: Rm2 - flow meter 2
#14: Rm3 - flow meter 3
#27: Rm4 - flow meter 4

#15: relay 1
#2:  relay 2
#4:  relay 3
#16: relay 4

substitutions:
  me: garden-water

esphome:
  name: ${me}
  comment: esp32 devkit

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: info

api:
  encryption:
    key: !secret esp_api_key

ota:
  password: !secret esp_ota_pw
  id: my_ota

prometheus:

web_server:
  port: 80

text_sensor:
  - platform: version
    name: ${me} ESPHome Version

switch:
  - platform: restart
    name: ${me} restart

  - platform: gpio
    # olla system
    name: ${me} valve 1
    icon: "mdi:valve"
    pin:
      number: 15
      inverted: yes
    
  - platform: gpio
    # SE raised bed
    name: ${me} valve 2
    icon: "mdi:valve"
    pin:
      number: 2
      inverted: yes

  - platform: gpio
    # SW raised bed 
    name: ${me} valve 3
    icon: "mdi:valve"
    pin:
      number: 4
      inverted: yes

  - platform: gpio
    # S raised bed
    name: ${me} valve 4
    icon: "mdi:valve"
    pin:
      number: 16
      inverted: yes

sensor:
  - platform: uptime
    name: ${me} uptime
    update_interval: 120s
    
  - platform: wifi_signal
    name: ${me} wifi signal
    update_interval: 120s

  - platform: pulse_counter
    pin: 13
    name: ${me} flow rate 1
    unit_of_measurement: 'gal/min'
    update_interval: 5s
    accuracy_decimals: 2
    filters:
      # 1928 pulses = 127 oz
      - multiply: 0.0005146200726141079 
    total:
      name: ${me} volume 1
      unit_of_measurement: 'gal'
      accuracy_decimals: 2
      filters: 
        - multiply: 0.0005146200726141079

  - platform: pulse_counter
    pin: 26 # was 12; bad idea
    name: ${me} flow rate 2
    unit_of_measurement: 'gal/min'
    update_interval: 5s
    accuracy_decimals: 2
    filters:
      # 1928 pulses = 127 oz
      - multiply: 0.0005146200726141079 
    total:
      name: ${me} volume 2
      unit_of_measurement: 'gal'
      accuracy_decimals: 2
      filters: 
        - multiply: 0.0005146200726141079

  - platform: pulse_counter
    pin: 14
    name: ${me} flow rate 3
    unit_of_measurement: 'gal/min'
    update_interval: 5s
    accuracy_decimals: 2
    filters:
      # 1928 pulses = 127 oz
      - multiply: 0.0005146200726141079 
    total:
      name: ${me} volume 3
      unit_of_measurement: 'gal'
      accuracy_decimals: 2
      filters: 
        - multiply: 0.0005146200726141079

  - platform: pulse_counter
    pin: 27
    name: ${me} flow rate 4
    unit_of_measurement: 'gal/min'
    update_interval: 5s
    accuracy_decimals: 2
    filters:
      # 1928 pulses = 127 oz
      - multiply: 0.0005146200726141079 
    total:
      name: ${me} volume 4
      unit_of_measurement: 'gal'
      accuracy_decimals: 2
      filters: 
        - multiply: 0.0005146200726141079
