# This is for a martin jerry mj-s01 wall switch
# on breaker 4A
substitutions:
  name: "hall-closet-light"
  me: "hall_closet_light"
  on_time: 300s

esphome:
  name: ${name}
  platform: ESP8266
  board: esp01_1m
  on_boot:
    priority: 200
    then:
      - output.turn_on: blue_led
      - output.turn_off: red_led
  comment: "MJ-S01"

wifi:
  ssid: !secret ssid2
  password: !secret password2

logger:

prometheus:

web_server:
  port: 80

api:

ota:

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: America/Chicago


text_sensor:
  - platform: version
    name: "ESPHome Version"


switch:
  - platform: restart
    name: "${name} restart"


output:
  - platform: gpio
    id: blue_led
    pin: GPIO5
    inverted: True
    
  - platform: gpio
    id: red_led
    pin: GPIO4
    inverted: True

  - platform: gpio
    id: relay
    pin: GPIO12


light:
  - platform: binary
    name: "Hall Closet Light"
    id: ${me}
    output: relay
    on_turn_on:
      - output.turn_off: blue_led
    on_turn_off:
      - output.turn_on: blue_led
      - output.turn_off: red_led


script:
  - id: inching
    then:
      - light.turn_on: ${me}
      - delay: ${on_time}
      - light.turn_off: ${me}


sensor:
  - platform: uptime
    name: ${name} uptime
    update_interval: 120s
    
  - platform: wifi_signal
    name: ${name} wifi signal
    update_interval: 120s


binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    id: button
    on_press:
      - if:
          condition:
            light.is_on: ${me}
          then:
            - script.stop: inching
            - light.turn_off: ${me}
          else:
            - script.execute: inching
    on_click:
      - min_length: 500ms
        max_length: 2000ms
        then:
          if:
            condition:
              script.is_running: inching
            then:
              - script.stop: inching
              - light.turn_on: ${me}
              - output.turn_off: blue_led
              - output.turn_on: red_led
