substitutions:
  me: oak-fairies

esphome:
  name: ${me}
  comment: tiny pico32

esp32:
  board: um_tinys3
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: info

api:
  encryption:
    key: !secret esp_api_key

ota:
  - platform: esphome
    password: !secret esp_ota_pw
    id: my_ota

web_server:
  port: 80

prometheus:

text_sensor:
  - platform: version
    name: ${me} ESPHome Version

switch:
  - platform: restart
    name: ${me} restart

sensor:
  - platform: uptime
    name: ${me} uptime
    update_interval: 120s
    
  - platform: wifi_signal
    name: wifi signal
    update_interval: 120s

light:
  - platform: esp32_rmt_led_strip
    name: ${me} lights
    rgb_order: RGB
    chipset: WS2811
    pin: GPIO2
    num_leds: 333 
    rmt_channel: 0
    effects:
      - addressable_rainbow:
      - addressable_rainbow:
          name: Rainbow 10 333
          speed: 10
          width: 500
      - addressable_color_wipe:
      - addressable_color_wipe:
          name: Color Wipe 1
          colors:
            - red: 50%
              green: 50%
              blue: 50%
              num_leds: 100
              gradient: true
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 1
          add_led_interval: 100ms
          reverse: false
      - addressable_scan:
      - addressable_scan:
          name: Scan 10ms 50w
          move_interval: 10ms
          scan_width: 50
      - addressable_twinkle:
      - addressable_twinkle:
          name: Twinkle 50% 4ms
          twinkle_probability: 50%
          progress_interval: 4ms
      - addressable_fireworks:
      - addressable_fireworks:
          name: Fireworks 32ms 50%
          update_interval: 32ms
          spark_probability: 50%
          use_random_color: false
          fade_out_rate: 120
