substitutions:
  me: oak-radar

esphome:
  name: ${me}
  comment: wemos mini

esp8266:
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

prometheus:

web_server:
  port: 80

logger:
  level: info

api:
  encryption:
    key: !secret esp_api_key

ota:
  - platform: esphome
    password: !secret esp_ota_pw
    id: my_ota

time:
  - platform: homeassistant
    timezone: America/Chicago

uart:
  tx_pin: GPIO4 # connect to LD2420 Rx pin
  rx_pin: GPIO2 # connect to LD2420 OT1 pin
  baud_rate: 115200

ld2420:

text_sensor:
  - platform: version
    name: ${me} ESPHome Version

  - platform: ld2420
    fw_version:
      name: LD2420 Firmware

switch:
  - platform: restart
    name: restart

sensor:
  - platform: uptime
    name: ${me} uptime
    update_interval: 120s
    
  - platform: wifi_signal
    name: ${me} wifi signal
    update_interval: 120s
    
  - platform: ld2420
    moving_distance:
      name : Moving Distance
      accuracy_decimals: 0
      filters:
        - clamp:
            min_value: 10
            max_value: 700
            ignore_out_of_range: true


binary_sensor:
  - platform: ld2420
    has_target:
      name: Presence

select:
  - platform: ld2420
    operating_mode:
      name: Operating Mode

number:
  - platform: ld2420
    presence_timeout:
      name: Detection Presence Timeout
    min_gate_distance:
      name: Detection Gate Minimum
    max_gate_distance:
      name: Detection Gate Maximum
    # See "Number" section below for detail
    gate_select:
      name: Select Gate to Set
    still_threshold:
      name: Set Still Threshold Value
    move_threshold:
      name: Set Move Threshold Value

button:
  - platform: ld2420
    apply_config:
      name: Apply Config
    factory_reset:
      name: Factory Reset
    restart_module:
      name: Restart Module
    revert_config:
      name: Undo Edits
