substitutions:
  name: olla-water
  on_time: 600s

esphome:
  name: ${name}
  comment: "TinyPico32"

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: !secret ssid2
  password: !secret password2

logger:
  level: info

api:

ota:

prometheus:

web_server:
  port: 80
  
time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: America/Chicago

text_sensor:
  - platform: version
    name: "ESPHome Version"

#esp32_ble_tracker:
#  scan_parameters:
#    interval: 1100ms
#    window: 1100ms
#    active: true

#bluetooth_proxy:
#  active: true


switch:
  - platform: restart
    name: ${name} restart

  - platform: gpio
    name: ${name}-valve
    id: valve
    pin: 21

sensor:
  - platform: uptime
    name: ${name} uptime
    update_interval: 120s
    
  - platform: wifi_signal
    name: ${name} wifi signal
    update_interval: 120s

  - platform: pulse_counter
    pin: 32
    name: ${name} flow rate
    internal: false
    unit_of_measurement: 'gal/min'
    update_interval: 5s
    accuracy_decimals: 2
    filters:
      # 1928 pulses = 127 oz
      - multiply: 0.0005146200726141079 
    total:
      name: ${name} volume
      unit_of_measurement: 'gal'
      accuracy_decimals: 2
      filters: 
        - multiply: 0.0005146200726141079

script:
  - id: inching
    then:
      - switch.turn_on: valve
      - delay: ${on_time}
      - switch.turn_off: valve
