substitutions:
  me: olla-water

esphome:
  name: ${me}
  comment: TinyPico32

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: !secret ssid2
  password: !secret password2

logger:
  level: info

api:
  encryption:
    key: !secret esp_api_key

ota:
  password: !secret esp_ota_pw
  id: my_ota

prometheus:

web_server:
  port: 80
  
time:
  - platform: homeassistant
    timezone: America/Chicago

text_sensor:
  - platform: version
    name: ${me} ESPHome Version

switch:
  - platform: restart
    name: ${me} restart

  - platform: gpio
    name: ${me} valve
    id: valve
    pin: 21

sensor:
  - platform: uptime
    name: ${me} uptime
    update_interval: 120s
    
  - platform: wifi_signal
    name: ${me} wifi signal
    update_interval: 120s

  - platform: pulse_counter
    pin: 32
    name: ${me} flow rate
    internal: false
    unit_of_measurement: 'gal/min'
    update_interval: 5s
    accuracy_decimals: 2
    filters:
      # 1928 pulses = 127 oz
      - multiply: 0.0005146200726141079 
    total:
      name: volume
      unit_of_measurement: 'gal'
      accuracy_decimals: 2
      filters: 
        - multiply: 0.0005146200726141079

script:
  - id: inching
    then:
      - switch.turn_on: valve
      - delay: 5min
      - switch.turn_off: valve
