substitutions:
  me: pool-level
  interval: 15s

esphome:
  name: ${me}
  comment: supermini esp32h2
  on_boot:
    then:
      - lambda: App.set_loop_interval(100);
      - script.execute: sensor_update_loop

external_components:
  - source: github://pr#12325
    components: [power_management]
    refresh: 1h
  - source: github://pr#11766
    components: [openthread]
    refresh: 1h
  - source:
      type: local
      path: components
    components: [nau7802_local, max17048, openthread_rssi]

esp32:
  variant: ESP32H2
  framework:
    type: esp-idf

logger:
  level: DEBUG
  baud_rate: 0

api:
  encryption:
    key: !secret esp_api_key

ota:
  - platform: esphome
    password: !secret esp_ota_pw
    id: my_ota

network:
  enable_ipv6: true

openthread:
  device_type: MTD
  force_dataset: True
  output_power: 12dBm
  poll_period: ${interval}
  tlv: !secret thread_tlv

i2c:
  sda: 14 # qwiic blue
  scl: 12 # qwiic yellow
  frequency: 100kHz

power_management:
  id: pm_id
  enable_light_sleep: true
  power_down_flash: true
  power_down_peripherals: false
  profiling: true

sensor:
  - platform: uptime
    id: uptime_sensor
    name: uptime
    update_interval: never

  - platform: openthread_rssi
    name: "Thread Parent RSSI"
    update_interval: 30s

  - platform: nau7802_local
    id: nau_raw
    name: nau_raw
    gain: 128
    ldo_voltage: 3.0V
    update_interval: never
    temperature:
      id: nau_temp_raw
      accuracy_decimals: 2

  - platform: template
    name: nau-temp
    id: nau_temp
    device_class: temperature
    unit_of_measurement: "°C"
    lambda: |-
      float x = id(nau_temp_raw).state;
      return ((3.177731e-10f) * x + 7.689528e-04f) * x + -2.398036e+02f;
    accuracy_decimals: 2
    update_interval: never

  - platform: template
    id: depth_sensor
    name: depth
    lambda: |-
      float t = id(nau_temp).state;
      float r = id(nau_raw).state;
      float zero = 567346 + -204482*t + 4031.2*pow(t,2);
      float cal100 = -2.1923e+06 + -20988.5*t + -168.027*pow(t,2);
      return 100.0f * (r - zero) / (cal100 - zero);    
    unit_of_measurement: mm
    state_class: measurement
    update_interval: never
    accuracy_decimals: 2

  - platform: max17048
    id: max17048_id
    update_interval: never
    battery_voltage:
      name: "Battery Voltage"
    battery_level:
      name: "Battery"

switch:
  - platform: template
    id: radio_always_on
    name: "Radio Always On"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      then:
        - logger.log: "Set Radio Always On"
        - openthread.pollperiod: 0s

    turn_off_action:
      then:
        - logger.log: "Set Radio Off When Idle"
        - openthread.pollperiod: !lambda "return (uint32_t)(id(sensor_interval).state * 1000);"

number:
  - platform: template
    id: sensor_interval
    name: "Sensor Interval"
    min_value: 5
    max_value: 3600
    step: 1
    unit_of_measurement: s
    optimistic: true
    restore_value: true
    initial_value: 15
    on_value:
      then:
        - if:
            condition:
              switch.is_off: radio_always_on
            then:
              - openthread.pollperiod: !lambda "return (uint32_t)(x * 1000);"
        - script.stop: sensor_update_loop
        - script.execute: sensor_update_loop

script:
  - id: sensor_update_loop
    mode: single
    then:
      - while:
          condition:
            lambda: return true;
          then:
            - component.update: uptime_sensor
            - component.update: nau_raw
            - component.update: nau_temp
            - component.update: depth_sensor
            - component.update: max17048_id
            - delay: !lambda "return (uint32_t)(id(sensor_interval).state * 1000);"

