substitutions:
  me: pool-level2 

esphome:
  name: ${me}
  comment: wemos d1-mini

esp8266:
  board: d1_mini
    
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: info

api:
  encryption:
    key: !secret esp_api_key

ota:
  - platform: esphome
    password: !secret esp_ota_pw
    id: my_ota

prometheus:

web_server:
  version: 3

time:
  - platform: homeassistant
    timezone: America/Chicago

text_sensor:
  - platform: version
    name: ${me} ESPHome Version

switch:
  - platform: restart
    name: ${me} restart

i2c:
  sda: GPIO4
  scl: GPIO5
  frequency: 200kHz

one_wire:
  - platform: gpio
    pin:
      number: GPIO2
      mode:
        input: true
        pullup: true

sensor:
  - platform: uptime
    name: ${me} uptime
    update_interval: 120s

  - platform: wifi_signal
    name: ${me} wifi signal
    update_interval: 120s

  # Resistive level sensor. 33.5 ohm full, 244 ohm empty
  # Connected as a wheatstone bridge with 10k resistors as the top of the bridge
  # and a 100 ohm resister across from the sensor
  # Rx:33, Vg:3.84 mV
  # Rx:90, Vg:0.572 mV
  # Rx:240, Vg:-7.98 mV
  - platform: nau7802
    name: "NAU7802"
    gain: 32
    samples_per_second: 10
    offset_calibration: 1800
    gain_calibration: 1
    ldo_voltage: "2.7V"
    update_interval: .125s
    unit_of_measurement: cnt
    filters:
      - sliding_window_moving_average:
          window_size: 50
          send_every: 50

  - platform: dallas_temp
    name: dt1
    address: 0xb23c01d07579b428
    accuracy_decimals: 2
    update_interval: 1s

  - platform: dallas_temp
    name: dt2
    address: 0xf701205f7aff6528
    accuracy_decimals: 2
    update_interval: 1s


