substitutions:
  me: pool-level
  interval: 15s

esphome:
  name: ${me}
  comment: supermini esp32h2
  on_boot:
    then:
      - lambda: App.set_loop_interval(100);

external_components:
  - source: github://pr#12325
    components: [power_management]
    refresh: 1h
  - source: github://pr#11766
    components: [openthread]
    refresh: 1h
  - source:
      type: local
      path: components
    components: [nau7802_local, max17048]

esp32:
  variant: ESP32H2
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_USJ_NO_AUTO_LS_ON_CONNECTION: n # doesn't seem to matter

logger:
  level: DEBUG
  #baud_rate: 0

api:
  encryption:
    key: !secret esp_api_key

ota:
  - platform: esphome
    password: !secret esp_ota_pw
    id: my_ota

network:
  enable_ipv6: true

openthread:
  device_type: MTD
  force_dataset: True
  output_power: 8dBm
  poll_period: ${interval}
  tlv: 0e080000000000010000000300000f4a0300001535060004001fffe00208d048b6c2bb035b310708fdc224ebeb1bd67f051031ef9e2d3d6fe3acff931e9e82bb14d2030e68612d7468726561642d313631620102161b0410625716294324d7a2013e2100d549ff0e0c0402a0f7f8

i2c:
  sda: 14 # qwiic blue
  scl: 12 # qwiic yellow
  frequency: 100kHz

one_wire:
  - platform: gpio
    pin:
      number: 11
      mode:
        input: true
        pullup: true

power_management:
  id: pm_id
  enable_light_sleep: true
  power_down_flash: true
  power_down_peripherals: false
  profiling: true

globals:
  - id: tare_count
    type: float
    restore_value: yes
    initial_value: "100000"

  - id: cal100_count
    type: float
    restore_value: yes
    initial_value: "200000"

sensor:
  - platform: uptime
    name: uptime
    update_interval: ${interval}

  - platform: nau7802_local
    id: nau_raw
    name: nau-raw
    gain: 128
    ldo_voltage: 3.0V
    update_interval: ${interval}
    temperature:
      id: nau_temp_raw
      name: nau_temp_raw
      accuracy_decimals: 2

  - platform: template
    name: nau-temp
    id: nau_temp
    device_class: temperature
    unit_of_measurement: "°C"
    lambda: |-
      float x = id(nau_temp_raw).state;
      return ((3.177731e-10f) * x + 7.689528e-04f) * x + -2.398036e+02f;
    accuracy_decimals: 2
    update_interval: ${interval}

  - platform: template
    id: nau_tc
    lambda: |-
      float tr = id(nau_temp_raw).state;
      float tr_ref = 314414.5f;
      float raw_offset = (((1.344351e-04f) * tr + -1.113397e+02f) * tr + 2.092379e+07f) - (((1.344351e-04f) * tr_ref + -1.113397e+02f) * tr_ref + 2.092379e+07f);
      return id(nau_raw).state - raw_offset;
    update_interval: ${interval}

  - platform: template
    name: depth
    device_class: distance
    lambda: return 100.0f * (id(nau_tc).state - id(tare_count)) / (id(cal100_count) - id(tare_count));
    unit_of_measurement: mm
    update_interval: ${interval}
    accuracy_decimals: 2

  - platform: max17048
    id: max17048_id
    update_interval: ${interval}
    battery_voltage:
      name: "Battery Voltage"
    battery_level:
      name: "Battery"

switch:
  - platform: template
    name: "Radio Always On"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      then:
        - logger.log: "Set Radio Always On"
        - openthread.pollperiod: 0s

    turn_off_action:
      then:
        - logger.log: "Set Radio Off When Idle"
        - openthread.pollperiod: ${interval}

button:
  - platform: template
    name: "0 mm Cal"
    on_press:
      - logger.log:
          format: "setting tare_count to %.1f"
          args: ['id(nau_raw).state']
      - lambda: 'id(tare_count) = id(nau_tc).state;'
  - platform: template
    name: "100 mm Cal"
    on_press:
      - logger.log:
          format: "setting cal100_count to %.1f"
          args: ['id(nau_raw).state']
      - lambda: 'id(cal100_count) = id(nau_tc).state;'
      
