# Vbat on the back of the board is connected to an 18650 LiIon cell
# Vbuss is connected to a 5VDC solar cell
# D0/A0/GPIO2 is connected to Vbat+ via a 100k/100k divider 

# Deep sleep current, around 60uA with the level sensor connected
# Awake current 30-80mA

substitutions:
  me: "pool-level"

esphome:
  name: ${me}
  comment: seeed esp32c3
  area: Pool

esp32:
  board: seeed_xiao_esp32c3
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: false
  reboot_timeout: 60s
  id: wifi_id
  power_save_mode: HIGH
  manual_ip: 
    static_ip: 192.168.2.26
    gateway: 192.168.2.1
    subnet: 255.255.255.0
    dns1: 192.168.2.1

web_server:
  version: 2

logger:
  level: DEBUG
  logs:
    sensor: ERROR
    dallas.temp.sensor: ERROR

ota:
  - platform: esphome
    password: !secret esp_ota_pw
    id: my_ota

api:
  encryption:
    key: !secret esp_api_key
  
text_sensor:
  - platform: version
    name: ${me} ESPHome Version

switch:
  - platform: restart
    name: ${me} restart

i2c:
  sda: GPIO6
  scl: GPIO7

one_wire:
  - platform: gpio
    pin: GPIO10

sensor:
  - platform: wifi_signal
    name: ${me} wifi signal
    id: snr
    update_interval: 120s

  - platform: internal_temperature
    name: ${me} internal temperature
    id: temp
    update_interval: 12s
    filters:
      - sliding_window_moving_average:
          window_size: 10
          send_every: 10
          send_first_at: 10

  - platform: adc
    # aka D0, Has a 100k/100k resistive divider to Vbat
    # Also note that the battery voltage drops about .15 V when under the 80mA load
    pin: GPIO2
    name: ${me} vbat
    id: vbat
    attenuation: 12db # full scale is 4.2V
    accuracy_decimals: 2
    update_interval: 1s
    filters:
      - multiply: 2
      - sliding_window_moving_average:
          window_size: 10
          send_every: 10
          send_first_at: 10

  - platform: honeywellabp2_i2c
    update_interval: 1s
    pressure:
      name: ${me} pressure
      id: pressure
      # default units are Pa. This is +-10"H2O as per the datasheet
      accuracy_decimals: 3
      min_pressure: -2490
      max_pressure: +2490
      transfer_function: "A"

  - platform: template
    name: ${me} level
    lambda: "return id(pressure).state;"
    unit_of_measurement: cm
    update_interval: 1s
    accuracy_decimals: 1
    filters:
      - offset: -9
      - multiply: 0.010197

  - platform: dallas_temp
    address: 0xd63c01d075a4ef28
    name: ${me} water temperature
    accuracy_decimals: 2
    update_interval: 120s
    unit_of_measurement: °C
