# This is for a sonoff basic switch module
substitutions:
  me: pool-lights
esphome:
  name: ${me}
  comment: Sonoff basic

esp8266:
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

prometheus:

web_server:
  port: 80

logger:
  level: info

api:
  encryption:
    key: !secret esp_api_key

ota:
  - platform: esphome
    password: !secret esp_ota_pw
    id: my_ota

time:
  - platform: homeassistant
    timezone: America/Chicago

text_sensor:
  - platform: version
    name: ${me} ESPHome Version

switch:
  - platform: restart
    name: ${me} restart

sensor:
  - platform: uptime
    name: ${me} uptime
    update_interval: 120s

  - platform: wifi_signal
    name: ${me} wifi signal
    update_interval: 120s

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: ${me} button
    on_press:
      - light.toggle: my_light

light:
  - platform: binary
    name: Pool Lights
    id: my_light
    output: relay

output:
  - platform: gpio
    pin: GPIO12
    id: relay

status_led:
  pin: GPIO13
