substitutions:
  me: porch-olla

esphome:
  name: ${me}
  comment: wemos d1-mini

esp8266:
  board: d1_mini

logger:
  level: info

api:
  encryption:
    key: !secret esp_api_key

ota:
  - platform: esphome
    password: !secret esp_ota_pw
    id: my_ota
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

prometheus:

web_server:
  port: 80

switch:
  - platform: restart
    name: ${me} restart
  
  - platform: gpio
    id: relay
    pin: D1
    name: ${me} valve
    icon: mdi:valve    

text_sensor:
  - platform: version
    name: ${me} ESPHome Version

sensor:
  - platform: uptime
    name: ${me} uptime
    update_interval: 120s
    
  - platform: wifi_signal
    name: ${me} wifi signal
    update_interval: 120s

  - platform: pulse_counter
    pin: D2
    name: ${me} flow rate
    internal: false
    unit_of_measurement: 'gal/min'
    update_interval: 5s
    accuracy_decimals: 2
    filters:
      - multiply: 0.000722 
    total:
      name: ${me} usage
      unit_of_measurement: 'gal'
      accuracy_decimals: 2
      filters: 
        - multiply: 0.000722
