# This is for a treatlife DS03 three way wall dimmer switch
substitutions:
  me: porch-fans-lights

esphome:
  name: ${me}
  comment: DS03

esp8266:
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: info
  baud_rate: 0 # dimmer uses serial

prometheus:

web_server:
  port: 80

api:
  encryption:
    key: !secret esp_api_key

ota:
  - platform: esphome
    password: !secret esp_ota_pw
    id: my_ota

uart:
  id: uart_bus
  baud_rate: 115200
  tx_pin: GPIO1
  rx_pin: GPIO3

tuya:

time:
  - platform: homeassistant
    timezone: America/Chicago

text_sensor:
  - platform: version
    name: ${me} ESPHome Version

switch:
  - platform: restart
    name: ${me} restart

sensor:
  - platform: uptime
    name: ${me} uptime
    update_interval: 120s

  - platform: wifi_signal
    name: ${me} wifi signal
    update_interval: 120s

light:
  - platform: "tuya"
    name: Porch Lights
    dimmer_datapoint: 10
    switch_datapoint: 9
    min_value: 100
    max_value: 1000

fan:
  - platform: "tuya"
    name: Porch Fans
    switch_datapoint: 1
    speed_datapoint: 3
    speed_count: 4
