# Wemos d1 mini
# DS18B20 on D3

substitutions:
  name: porch-1

esphome:
  name: ${name}
  platform: ESP8266
  board: d1_mini
  comment: "wemos d1-mini"

wifi:
  ssid: !secret ssid2
  password: !secret password2

logger:

api:

ota:

prometheus:

web_server:
  port: 80

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: America/Chicago

text_sensor:
  - platform: version
    name: "ESPHome Version"

switch:
  - platform: restart
    name: ${name} restart

sensor:
  - platform: uptime
    name: ${name} uptime
    update_interval: 120s

  - platform: wifi_signal
    name: ${name} wifi signal
    update_interval: 120s

  - platform: dallas
    address: 0xBB0118776477FF28
    name: ${name} temperature
    accuracy_decimals: 2
    filters:
    - lambda: return x * (9.0/5.0) + 32.0;
    unit_of_measurement: °F

dallas:
  - pin: D3
