# This is for a ElectroDragon dimmer operating in RGB mode
# https://www.electrodragon.com/product/esp-led-strip-board/
# IO0: on board flash button
# IO14: W
# IO12: B
# IO13: G
# IO15: R
# IO16: status LED
substitutions:
  me: porch-fairies

esphome:
  name: ${me}
  comment: ElectroDragon

esp8266:
  board: esp12e

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

prometheus:

web_server:
  port: 80

logger:
  level: info

api:
  encryption:
    key: !secret esp_api_key

ota:
  password: !secret esp_ota_pw
  id: my_ota

time:
  - platform: homeassistant
    timezone: America/Chicago

text_sensor:
  - platform: version
    name: ${me} ESPHome Version

switch:
  - platform: restart
    name: ${me} restart

sensor:
  - platform: uptime
    name: ${me} uptime
    update_interval: 120s

  - platform: wifi_signal
    name: ${me} wifi signal
    update_interval: 120s

output:
  - platform: esp8266_pwm
    pin: GPIO12
    frequency: 1000 Hz
    id: blue_pwm

  - platform: esp8266_pwm
    pin: GPIO13
    frequency: 1000 Hz
    id: green_pwm

  - platform: esp8266_pwm
    pin: GPIO14
    frequency: 1000 Hz
    id: white_pwm

  - platform: esp8266_pwm
    pin: GPIO15
    frequency: 1000 Hz
    id: red_pwm

light:
  - platform: monochromatic
    name: N. Porch fairies
    output: green_pwm

  - platform: monochromatic
    name: S. Porch fairies
    output: blue_pwm