substitutions:
  me: tank-level2

esphome:
  name: ${me}
  comment: tinys3

esp32:
  board: um_tinys3

logger:
  level: info
  logs:
    ads1115: info

api:
  encryption:
    key: !secret esp_api_key

ota:
  - platform: esphome
    password: !secret esp_ota_pw
    id: my_ota
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:
  port: 80

prometheus:

switch:
  - platform: restart
    name: ${me} restart

one_wire:
  - platform: gpio
    pin:
      number: GPIO4
      mode:
        input: true
        pullup: true
    

i2c:
  sda: GPIO5
  scl: GPIO21
  scan: true
  id: bus_a

ads1115:
  - address: 0x48

sensor:
  - platform: uptime
    name: ${me} uptime
    update_interval: 120s
    
  - platform: wifi_signal
    name: ${me} wifi signal
    update_interval: 120s

  - platform: ads1115
    multiplexer: 'A0_GND'
    gain: 4.096
    name: ${me} throw-in-pressure
    id: tip
    unit_of_measurement: V
    update_interval: 0.5s
    filters:
      - sliding_window_moving_average:
          # .5 s * 500 = 250 sec
          window_size: 500
          send_every: 500

  # Full is 2083mm (82")
  # Note that this cal is dependant on the gain/zero set on the 4-20mA -> V converter
  - platform: template
    name: ${me} water level
    lambda: return id(tip).state;
    unit_of_measurement: mm
    filters:
      - calibrate_linear:
          method: least_squares
          datapoints:
            # with stick on tape measure unless otherwise noted
            - -0.100 -> 0      # zero point 
            #- 3.040 -> 58.62  # measured on mech gauge, 20250111
            #- 3.142 -> 63.5   # 20250130
            #- 3.908 -> 78.625 # 20250324
            #- 3.912 -> 77.75  # 20250211
            #- 3.927 -> 79.375 # 20250223
            #- 3.968 -> 80.000 # 20250212
            - 4.087 -> 82.250 # 20250330, full
      - multiply: 25.4


  - platform: dallas_temp
    address: 0x773c01d07583a328
    name: Rainwater lower tank water temperature
    accuracy_decimals: 2
    unit_of_measurement: °C

  - platform: dallas_temp
    address: 0xaf012038a4b60828
    name: 4-20 temperature
    accuracy_decimals: 2
    unit_of_measurement: °C

