# This is for a sonoff POW R1 switch module
# https://www.esphome-devices.com/devices/Sonoff-POW-R1
substitutions:
  name: "tank-tapes"

esphome:
  name: ${name}
  platform: ESP8266
  board: esp01_1m
  comment: "Sonoff POW R1"

wifi:
  ssid: !secret ssid2
  password: !secret password2

prometheus:

web_server:
  port: 80

logger:

api:

ota:

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: America/Chicago


text_sensor:
  - platform: version
    name: "ESPHome Version"


binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: Tank Tapes Button
    on_press:
      - switch.toggle: fakebutton

  - platform: template
    name: Tank Tapes Running
    filters:
      - delayed_off: 15s
    lambda: |-
      if (isnan(id(power).state)) {
        return {};
      } else if (id(power).state > 4) {
        // Running
        return true;
      } else {
        // Not running
        return false;
      }


sensor:
  - platform: uptime
    name: ${name} uptime
    update_interval: 120s
    
  - platform: wifi_signal
    name: ${name} wifi signal
    update_interval: 120s

  - platform: hlw8012
    sel_pin: 5
    cf_pin: 14
    cf1_pin: 13
    update_interval: 2s
    current:
      name: Tank Tapes Current
    voltage:
      name: Tank Tapes Voltage
    power:
      name: Tank Tapes Power
      id: power
      on_value_range:
        - above: 4.0
          then:
            - light.turn_on: led
        - below: 3.0
          then:
            - light.turn_off: led


switch:
  - platform: restart
    name: "${name} restart"

  - platform: template
    name: "Tank Tapes"
    optimistic: true
    id: fakebutton
    turn_on_action:
      - switch.turn_on: relay
      - light.turn_on: led
    turn_off_action:
      - switch.turn_off: relay
      - light.turn_off: led

  - platform: gpio
    id: relay
    pin: GPIO12


output:
  - platform: esp8266_pwm
    id: pow_blue_led
    pin:
      number: GPIO15
      inverted: True


light:
  - platform: monochromatic
    output: pow_blue_led
    id: led
