# hardware wemos d1-mini with a string of DS18B20 sensors
substitutions:
  me: tank-temps

esphome:
  name: ${me}
  comment: "wemos d1-mini"

esp8266:
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: info

api:
  encryption:
    key: !secret esp_api_key

ota:
  - platform: esphome
    password: !secret esp_ota_pw
    id: my_ota

prometheus:

web_server:
  port: 80

time:
  - platform: homeassistant
    timezone: America/Chicago

text_sensor:
  - platform: version
    name: ${me} ESPHome Version

switch:
  - platform: restart
    name: ${me} restart

one_wire:
  - platform: gpio
    pin: D3

sensor:
  - platform: uptime
    name: ${me} uptime
    update_interval: 120s

  - platform: wifi_signal
    name: ${me} wifi signal
    update_interval: 120s

  - platform: dallas_temp
    address: 0x590119387D980028
    name: tank into ground
    accuracy_decimals: 2
    unit_of_measurement: 째C

  - platform: dallas_temp
    address: 0xC00119387D765A28
    name: tank ambient
    accuracy_decimals: 2
    unit_of_measurement: 째C

  - platform: dallas_temp
    address: 0x70011939F989F928
    name: tank pump head
    accuracy_decimals: 2
    unit_of_measurement: 째C

  - platform: dallas_temp
    address: 0xFB011939FFAF1328
    name: tank check valve
    accuracy_decimals: 2
    unit_of_measurement: 째C
