# hardware wemos d1-mini with a string of DS18B20 sensors
substitutions:
  me: tank-temps

esphome:
  name: ${me}
  comment: "wemos d1-mini"
  on_boot:
    - lambda: |-
        id(my_ota).set_auth_password("9f47a47302bb0eb644fa82fe1d75c67a");

esp8266:
  board: d1_mini

wifi:
  ssid: !secret ssid2
  password: !secret password2

logger:
  level: info

api:
  encryption:
    key: !secret esp_api_key

ota:
  password: "98990a48086e1c416ed715916cea6066"
  id: my_ota

prometheus:

web_server:
  port: 80

time:
  - platform: homeassistant
    timezone: America/Chicago

text_sensor:
  - platform: version
    name: ${me} ESPHome Version

switch:
  - platform: restart
    name: ${me} restart

sensor:
  - platform: uptime
    name: ${me} uptime
    update_interval: 120s

  - platform: wifi_signal
    name: ${me} wifi signal
    update_interval: 120s

  - platform: dallas
    address: 0x590119387D980028
    name: tank into ground
    accuracy_decimals: 2
    unit_of_measurement: 째C

  - platform: dallas
    address: 0xC00119387D765A28
    name: tank ambient
    accuracy_decimals: 2
    unit_of_measurement: 째C

  - platform: dallas
    address: 0x70011939F989F928
    name: tank pump head
    accuracy_decimals: 2
    unit_of_measurement: 째C

  - platform: dallas
    address: 0xFB011939FFAF1328
    name: tank check valve
    accuracy_decimals: 2
    unit_of_measurement: 째C

dallas:
  pin:
    number: D3
    mode:
      input: true
      pullup: true
