substitutions:
  me: tank-level

esphome:
  name: ${me}
  comment: wemos d1-mini

esp8266:
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: info

api:
  encryption:
    key: !secret esp_api_key

ota:
  - platform: esphome
    password: !secret esp_ota_pw
    id: my_ota

web_server:
  port: 80

prometheus:

time:
  - platform: homeassistant
    timezone: America/Chicago

uart:
  rx_pin: D7
  baud_rate: 9600

dallas:
  - pin: D3

switch:
  - platform: restart
    name: ${me} restart

text_sensor:
  - platform: version
    name: ${me} ESPHome Version

sensor:
  - platform: uptime
    name: ${me} uptime
    update_interval: 120s

  - platform: wifi_signal
    name: ${me} wifi signal
    update_interval: 120s

# 3/1/2020 manually measured the level as being 184 mm down from full,
# the hrxl read 475, 291 mm offsset
  - platform: "hrxl_maxsonar_wr"
    name: Rainwater tank level
    # Tweak the filters for your application
    filters:
      - sliding_window_moving_average:
          window_size: 12
          send_every: 12
      - or:
        - throttle: "20min"
        - delta: 0.02
      - lambda: return x*1000;
    accuracy_decimals: 1
    unit_of_measurement: mm

  - platform: dallas
    address: 0xe203186bcbfaff28
    name: Rainwater tank water temperature
    accuracy_decimals: 2
    unit_of_measurement: °C
