substitutions:
  me: tr1

esphome:
  name: ${me}
  comment: supermini esp32h2

esp32:
  variant: ESP32H2
  framework:
    type: esp-idf

logger:
  level: DEBUG

api:
  encryption:
    key: !secret esp_api_key

ota:
  - platform: esphome
    password: !secret esp_ota_pw
    id: my_ota

network:
  enable_ipv6: true

openthread:
  device_type: FTD
  force_dataset: True
  output_power: 20dBm
  tlv: 0e080000000000010000000300000f4a0300001535060004001fffe00208d048b6c2bb035b310708fdc224ebeb1bd67f051031ef9e2d3d6fe3acff931e9e82bb14d2030e68612d7468726561642d313631620102161b0410625716294324d7a2013e2100d549ff0e0c0402a0f7f8

sensor:
  - platform: uptime
    name: uptime
    update_interval: 5s

text_sensor:
  - platform: openthread_info
    ip_address:
      name: "Thread IP Address"
    channel:
      name: "Thread Channel"
    role:
      name: "Thread Device Role"
