substitutions:
  me: tr1

esphome:
  name: ${me}
  comment: supermini esp32h2

esp32:
  variant: ESP32H2
  framework:
    type: esp-idf

logger:
  level: DEBUG

api:
  encryption:
    key: !secret esp_api_key

ota:
  - platform: esphome
    password: !secret esp_ota_pw
    id: my_ota

network:
  enable_ipv6: true

openthread:
  device_type: FTD
  force_dataset: True
  output_power: 20dBm
  tlv: !secret thread_tlv

external_components:
  - source:
      type: local
      path: components
    components: [max17048, openthread_rssi]

i2c:
  sda: 14 # qwiic green
  scl: 12 # qwiic yellow
  frequency: 100kHz

openthread_rssi:
  update_interval: 15s

sensor:
  - platform: uptime
    name: uptime
    update_interval: 5s
    
  - platform: max17048
    id: max17048_id
    update_interval: 60s
    battery_voltage:
      name: "Battery Voltage"
    battery_level:
      name: "Battery"

text_sensor:
  - platform: openthread_info
    ip_address:
      name: "Thread IP Address"
    channel:
      name: "Thread Channel"
    role:
      name: "Thread Device Role"
