substitutions:
  me: tree-fairy-h

esphome:
  name: ${me}
  comment: wemos d1 mini?

esp8266:
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: info

api:
  encryption:
    key: !secret esp_api_key

ota:
  password: !secret esp_ota_pw
  id: my_ota

web_server:
  port: 80

prometheus:

text_sensor:
  - platform: version
    name: ${me} ESPHome Version

switch:
  - platform: restart
    name: ${me} restart

sensor:
  - platform: uptime
    name: ${me} uptime
    update_interval: 120s
    
  - platform: wifi_signal
    name: wifi signal
    update_interval: 120s

# Specify the two pins of the h-bridge as PWM pins
output:
  - platform: esp8266_pwm
    id: pina
    pin: GPIO16
  - platform: esp8266_pwm
    id: pinb
    pin: GPIO5

# Create a light using the hbridge
light:
  - platform: hbridge
    id: mainlight
    name: Tree Fairy H Light
    pin_a: pina
    pin_b: pinb
    