esphome:
  name: tree-fairy-h
  friendly_name: tree-fairy-h

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "KbvNsCIsT9SzK7IkM2djuyinGaJweB4S4wiwwz8m25g="

ota:
  password: "e38da83369ec4201387f5760fb5c6718"

web_server:
  port: 80
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

text_sensor:
  - platform: version
    name: "ESPHome Version"

switch:
  - platform: restart
    name: Restart

sensor:
  - platform: uptime
    name: Uptime
    update_interval: 120s
    
  - platform: wifi_signal
    name: wifi signal
    update_interval: 120s

# Specify the two pins of the h-bridge as PWM pins
output:
  - platform: esp8266_pwm
    id: pina
    pin: GPIO16
  - platform: esp8266_pwm
    id: pinb
    pin: GPIO5

# Create a light using the hbridge
light:
  - platform: hbridge
    id: mainlight
    name: "Tree Fairy H Light"
    pin_a: pina
    pin_b: pinb
    