esphome:
  name: tree-fairies
  friendly_name: Tree Fairies
  platform: ESP8266
  board: esp01_1m
  comment: "H801"

wifi:
  ssid: !secret ssid2
  password: !secret password2

prometheus:

web_server:
  port: 80

logger:
  level: info

api:
  encryption:
    key: "aIgBGyqR68z1R8rTCrlFEtcjhbSwjloRG0kVKS3wHTk="

ota:
  password: "wdQQvlWHXgcwnxvGsYxFWYSEnPFx6IHpt0ogzz2COPA="

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: America/Chicago

text_sensor:
  - platform: version
    name: "ESPHome Version"

switch:
  - platform: restart
    name: "${name} restart"

sensor:
  - platform: uptime
    name: ${name} uptime
    update_interval: 120s
    
  - platform: wifi_signal
    name: ${name} wifi signal
    update_interval: 120s
    
output:
  - platform: esp8266_pwm
    pin: GPIO15
    frequency: 1000 Hz
    id: pwm
    
light:
  - platform: monochromatic
    name: "Tree fairies"
    output: pwm
