substitutions:
  me: water-meter

esphome:
  name: ${me}
  comment: seeed xiao esp32c3

preferences:
  flash_write_interval: 5min

globals:
  - id: total_pulses
    type: float
    restore_value: yes

esp32:
  board: seeed_xiao_esp32c3
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  # The xiao esp32c3 seems to hang on reboot w/o a connected console
  # this seems to get around that. whatever
  baud_rate: 0
  level: info

api:
  encryption:
    key: !secret esp_api_key

ota:
  password: !secret esp_ota_pw
  id: my_ota

prometheus:

web_server:
  port: 80

switch:
  - platform: restart
    name: ${me} restart

dallas:
  - pin: 8

sensor:
  - platform: uptime
    name: ${me} uptime
    update_interval: 120s
    
  - platform: wifi_signal
    name: ${me} wifi signal
    update_interval: 120s
    filters:
      - sliding_window_moving_average:
          # hold 15 measurements, taken every 5 seconds
          window_size: 15
          # every 15 seconds, send the updated result..
          send_every: 15

  - platform: pulse_meter
    id: pulse_meter_id
    pin: 20
    unit_of_measurement: 'gpm'
    name: ${me} flow rate
    accuracy_decimals: 2
    timeout: 5s
    filters:
      - multiply: 0.008787
    total:
      name: ${me} usage
      unit_of_measurement: "G"
      accuracy_decimals: 2
      filters:
        - lambda: |-
            id(total_pulses) = id(total_pulses)+0.00878;
            //id(total_pulses) = 239016; // cumulative as of 10/8/2023
            return id(total_pulses);

  - platform: dallas
    address: 0x78000801edbbb610
    name: ${me} board temperature
    accuracy_decimals: 2
    unit_of_measurement: °C

  - platform: dallas
    address: 0x2c01187768f4ff28
    name: ${me} meter temperature
    accuracy_decimals: 2
    unit_of_measurement: °C
    
