substitutions:
  name: "water-meter"

esphome:
  name: "water-meter"
  friendly_name: "water-meter"
  comment: "seeed xiao esp32c3"

preferences:
  flash_write_interval: 5min

globals:
  - id: total_pulses
    type: float
    restore_value: yes

esp32:
  board: seeed_xiao_esp32c3
  
logger:
  # The xiao esp32c3 seems to hang on reboot w/o a connected console
  # this seems to get around that. whatever
  baud_rate: 0
  level: debug

api:
  encryption:
    key: "SlhkErjfbCnikT6z6/u/jZ0TJytQy6ZLDdHeASL6t5o="

ota:
  password: "a91c256e79428cf90c6eeeca7cd35fe8"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

prometheus:

web_server:
  port: 80

switch:
  - platform: restart
    name: "${name} restart"

dallas:
  - pin: 8

sensor:
  - platform: uptime
    name: ${name} uptime
    update_interval: 120s
    
  - platform: wifi_signal
    name: ${name} wifi signal
    update_interval: 120s
    filters:
      - sliding_window_moving_average:
          # hold 15 measurements, taken every 5 seconds
          window_size: 15
          # every 15 seconds, send the updated result..
          send_every: 15

  - platform: pulse_meter
    id: pulse_meter_id
    pin: 20
    unit_of_measurement: 'gpm'
    name: '${name} Flow Rate'
    accuracy_decimals: 2
    timeout: 5s
    filters:
      - multiply: 0.008787
    total:
      name: "${name} Usage"
      unit_of_measurement: "G"
      accuracy_decimals: 2
      filters:
        - lambda: |-
            id(total_pulses) = id(total_pulses)+0.00878;
            //id(total_pulses) = 239016; // cumulative as of 10/8/2023
            return id(total_pulses);

  - platform: dallas
    address: 0x78000801edbbb610
    name: ${name} board
    accuracy_decimals: 2
    filters:
    - lambda: return x * (9.0/5.0) + 32.0;
    unit_of_measurement: °F
