substitutions:
  me: water-meter

esphome:
  name: ${me}
  comment: seeed xiao esp32c3
  on_boot:
    priority: -100.0
    then:
      - pulse_meter.set_total_pulses: 
          id: pm
          value: !lambda return id(previous_usage);

preferences:
  flash_write_interval: 5min

globals:
  - id: previous_usage
    type: double
    restore_value: true
    initial_value: '104927' # 922 gal as of 3/3/2025

esp32:
  board: seeed_xiao_esp32c3
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  # The xiao esp32c3 seems to hang on reboot w/o a connected console
  # this seems to get around that. whatever
  baud_rate: 0
  level: debug
  logs:
    sensor: info
    wifi: info

api:
  encryption:
    key: !secret esp_api_key

ota:
  - platform: esphome
    password: !secret esp_ota_pw
    id: my_ota

prometheus:

web_server:
  port: 80

switch:
  - platform: restart
    name: ${me} restart

one_wire:
  - platform: gpio
    pin: 8

text_sensor:
  - platform: version
    name: ${me} ESPHome Version

sensor:
  - platform: uptime
    name: ${me} uptime
    update_interval: 120s
    
  - platform: wifi_signal
    name: ${me} wifi signal
    update_interval: 120s
    filters:
      - sliding_window_moving_average:
          # hold 15 measurements, taken every 5 seconds
          window_size: 15
          # every 15 seconds, send the updated result..
          send_every: 15

  - platform: template
    name: ${me} previous_usage
    lambda: !lambda return id(previous_usage);

  - platform: pulse_meter
    pin: 20
    unit_of_measurement: 'gpm'
    id: pm
    name: ${me} flow rate
    accuracy_decimals: 2
    timeout: 5s
    filters:
      - multiply: 0.008787
    total:
      name: ${me} total usage
      id: total_usage
      unit_of_measurement: 'gal'
      accuracy_decimals: 2
      filters:
        - multiply: 0.008787
      on_value:
        then:
          - globals.set: 
              id: previous_usage
              value: !lambda return id(total_usage).raw_state;

  - platform: dallas_temp
    address: 0x78000801edbbb610
    name: ${me} board temperature
    id: t1
    accuracy_decimals: 2
    unit_of_measurement: °C

  - platform: dallas_temp
    address: 0x2c01187768f4ff28
    name: ${me} meter temperature
    accuracy_decimals: 2
    unit_of_measurement: °C
    
