substitutions:
  me: water-meter

esphome:
  name: ${me}
  comment: seeed xiao esp32c3
  on_boot:
    priority: -100.0
    then:
      - logger.log: ${me} is connected!

preferences:
  flash_write_interval: 5min

globals:
  - id: usage
    type: double
    restore_value: yes

esp32:
  board: seeed_xiao_esp32c3
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  # The xiao esp32c3 seems to hang on reboot w/o a connected console
  # this seems to get around that. whatever
  baud_rate: 0
  level: info

api:
  encryption:
    key: !secret esp_api_key

ota:
  - platform: esphome
    password: !secret esp_ota_pw
    id: my_ota

prometheus:

web_server:
  port: 80

switch:
  - platform: restart
    name: ${me} restart

one_wire:
  - platform: gpio
    pin: 8

text_sensor:
  - platform: version
    name: ${me} ESPHome Version

sensor:
  - platform: uptime
    name: ${me} uptime
    update_interval: 120s
    
  - platform: wifi_signal
    name: ${me} wifi signal
    update_interval: 120s
    filters:
      - sliding_window_moving_average:
          # hold 15 measurements, taken every 5 seconds
          window_size: 15
          # every 15 seconds, send the updated result..
          send_every: 15

  - platform: pulse_meter
    pin: 20
    unit_of_measurement: 'gpm'
    id: pm
    name: ${me} flow rate
    accuracy_decimals: 2
    timeout: 5s
    filters:
      - multiply: 0.008787
    total:
      name: ${me} current usage
      id: pmt
      unit_of_measurement: 'gal'
      accuracy_decimals: 2
      filters:
        - multiply: 0.008787

  - platform: template
    name: ${me} temp usage
    accuracy_decimals: 2
    update_interval: 10s
    unit_of_measurement: "gal"
    lambda: |-
      id(usage) = id(pmt).state;
      return id(usage);

  - platform: dallas_temp
    address: 0x78000801edbbb610
    name: ${me} board temperature
    accuracy_decimals: 2
    unit_of_measurement: °C

  - platform: dallas_temp
    address: 0x2c01187768f4ff28
    name: ${me} meter temperature
    accuracy_decimals: 2
    unit_of_measurement: °C
    
