substitutions:
  name: well-meter

esphome:
  name: ${name}
  comment: "wemos d1-mini"

esp8266:
  board: d1_mini

# Enable logging
logger:
  level: info
# Enable Home Assistant API
api:
  encryption:
    key: "93PJM2Lrfri3xHGsLADZR+P9wcKXDo3h6Vu883jodZ4="

ota:
  password: "00b6f47bddb03459c5326e6d216b18e5"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

prometheus:

web_server:
  port: 80

switch:
  - platform: restart
    name: ${name} restart

sensor:
  - platform: uptime
    name: ${name} uptime
    update_interval: 120s
    
  - platform: wifi_signal
    name: ${name} wifi signal
    update_interval: 120s

  - platform: pulse_counter
    pin: D2
    name: ${name} flow rate
    internal: false
    unit_of_measurement: 'gal/min'
    update_interval: 5s
    accuracy_decimals: 2
    filters:
      - multiply: 0.000722 
    total:
      name: ${name} volume
      unit_of_measurement: 'gal'
      accuracy_decimals: 2
      filters: 
        - multiply: 0.000722
