esphome:
  name: esp32s3
  friendly_name: esp32s3

esp32:
  board: seeed_xiao_esp32s3
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: info

ota:
  - platform: esphome
    password: !secret esp_ota_pw

web_server:
  port: 80
  version: 3

i2c:
  sda: GPIO5
  scl: GPIO6

one_wire:
  - platform: gpio
    pin: GPIO9

sensor:
  - platform: dallas_temp
    name: t1
    # sensor by pressure sensor
    address: 0x33011877a466ff28
    update_interval: 10s
  - platform: dallas_temp
    name: t2
    # by water
    address: 0xe9011877b40fff28
    update_interval: 10s
  - platform: honeywellabp2_i2c
    address: 0x28
    pressure:
      name: pressure
      id: p
      min_pressure: -60
      max_pressure: 60
      transfer_function: "A"
      unit_of_measurement: mBar
      accuracy_decimals: 3
  - platform: template
    lambda: "return id(p).state;"
    name: level
    update_interval: 10s
    unit_of_measurement: cm
    filters: 
      - multiply: 1.0197

