esphome:
  name: pool-boy
  friendly_name: pool-boy

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Ky39HSE0WDjN0yzUPF6kBc60nne+YbfWiI+UYUrMgAA="

ota:
  - platform: esphome
    password: "b4ea70a198e222d57b1c4efe74514417"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Pool-Boy Fallback Hotspot"
    password: "V91sjZjIRYGP"

captive_portal:

web_server:
  port: 80
  version: 3

text_sensor:
  - platform: version
    name: ESPHome Version

output:
  - platform: gpio
    pin: GPIO23
    id: output_led

light:
  - platform: binary
    id: light_led
    name: LED
    output: output_led

binary_sensor:
  - platform: gpio
    pin: GPIO0
    name: io0 button

switch:
  - platform: restart
    name: restart

  - platform: gpio
    pin: GPIO16
    id: relay_1
    name: Relay 1

  - platform: gpio
    pin: GPIO17
    id: relay_2
    name: Relay 2

sensor:
  - platform: uptime
    name: uptime
    update_interval: 120s
    
  - platform: wifi_signal
    name: wifi signal
    update_interval: 120s
