# wemos d1 mini w oled 0.66 shield (SSD1306 driver on I2C 0x3c)
# 64x48 pixels across
# i2c buttons at i2c 0x31
# HX711 interface to strain gauge

substitutions:
  me: pool-level2 

esphome:
  name: ${me}
  comment: wemos d1-mini

esp8266:
  board: d1_mini
    
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: info

api:
  encryption:
    key: !secret esp_api_key

ota:
  - platform: esphome
    password: !secret esp_ota_pw
    id: my_ota

prometheus:

web_server:
  version: 3

time:
  - platform: homeassistant
    timezone: America/Chicago

text_sensor:
  - platform: version
    name: ${me} ESPHome Version

switch:
  - platform: restart
    name: ${me} restart

i2c:
  sda: GPIO4
  scl: GPIO5
  frequency: 200kHz

one_wire:
  - platform: gpio
    pin:
      number: D3
      mode:
        input: true
        pullup: true

sensor:
  - platform: uptime
    name: ${me} uptime
    update_interval: 120s

  - platform: wifi_signal
    name: ${me} wifi signal
    update_interval: 120s

  # Milone 12" eTape: 400-2k resistance nom, 2k ref nom
  # ref resistance measured as 2.54k
  # Connected as a wheatstone bridge with 2k resistors as the top of the bridge
  # out of water, -27.9 mv, 133.8mv in 145 mm of water
  - platform: nau7802
    name: "NAU7802"
    gain: 1
    samples_per_second: 10
    offset_calibration: 163000
    gain_calibration: 1
    ldo_voltage: "2.7V"
    update_interval: 1s
    unit_of_measurement: cnt
