substitutions:
  me: rgb-ball-1

esphome:
  name: ${me}
  comment: electrodragon esp32-c3

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip: 
    static_ip: 192.168.2.216
    gateway: 192.168.2.1
    subnet: 255.25.255.0

logger:
  level: info

api:
  encryption:
    key: !secret esp_api_key

ota:
  - platform: esphome
    password: !secret esp_ota_pw
    id: my_ota

prometheus:

web_server:

time:
  - platform: homeassistant
    timezone: America/Chicago

text_sensor:
  - platform: version
    name: ${me} ESPHome Version

switch:
  - platform: restart
    name: ${me} restart

output:
  - platform: ledc
    pin: GPIO7
    id: red
  - platform: ledc
    pin: GPIO6
    id: green
  - platform: ledc
    pin: GPIO5
    id: blue

light:
  - platform: rgb
    name: ${me}
    red: red
    green: green
    blue: blue
