# This is for a sonoff S31 power measuring socket (not the lite version)
substitutions:
  me: "spare-switch"

esphome:
  name: ${me}
  comment: "Sonoff S31"

esp8266:
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

prometheus:

web_server:
  port: 80

logger:
  baud_rate: 0 # required for the cse7766 to work
  level: info

ota:
  - platform: esphome
    password: "bff5f4b132c436d1a87c80d25baadced"

time:
  - platform: sntp
    id: sntp_time
    timezone: America/Chicago

number:
  - platform: template
    name: ap_closed
    max_value: 5000
    min_value: 0
    step: 1
    set_action:
      then:
        - switch.turn_on:
            id: relay

switch:
  - platform: restart
    name: "${me} restart"

  - platform: gpio
    name: "${me} relay"
    pin: GPIO12
    restore_mode: RESTORE_DEFAULT_ON
    id: relay
    icon: "mdi:power-socket-us"

sensor:
  - platform: uptime
    name: ${me} uptime
    update_interval: 120s
    
  - platform: wifi_signal
    name: ${me} wifi signal
    update_interval: 120s
    
  - platform: cse7766
    current:
      name: "${me} current"
      accuracy_decimals: 2
      filters:
        multiply: 0.951
    voltage:
      name: "${me} voltage"
      accuracy_decimals: 1
    power:
      name: "${me} power"
      id: power
      accuracy_decimals: 0
      filters:
        multiply: 0.951

  - platform: total_daily_energy
    name: ${me} daily energy
    power_id: power
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${me} button"
    on_press:
      - switch.toggle: relay

# Example button configuration
button:
  - platform: template
    name: Livingroom Lazy Mood
    id: my_button

    # Optional variables:
    icon: "mdi:emoticon-outline"
    on_press:
      - logger.log: "Button pressed"

status_led:
  pin: GPIO13

uart:
  rx_pin: RX
  baud_rate: 4800
  parity: even

