substitutions:
  me: therm1

esphome:
  name: ${me}
  comment: wemos d1 mini

esp8266:
  board: d1_mini

logger:
  level: info

api:
  encryption:
    key: !secret esp_api_key

ota:
  password: !secret esp_ota_pw
  id: my_ota

web_server:
  port: 80

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

time:
  - platform: homeassistant
    timezone: America/Chicago

text_sensor:
  - platform: version
    name: ${me} ESPHome Version

switch:
  - platform: restart
    name: ${me} restart

sensor:
  - platform: uptime
    name: ${me} uptime
    update_interval: 120s

  - platform: wifi_signal
    name: ${me} wifi signal
    update_interval: 120s

  - platform: dallas
    address: 0x5201205f7bdb7c28
    name: ${me} t1
    accuracy_decimals: 2
    unit_of_measurement: °C

  - platform: dallas
    address: 0xbb3c01e076ec5a28
    name: ${me} t2
    accuracy_decimals: 2
    unit_of_measurement: °C

dallas:
  - pin: D3
    update_interval: 10s
