# This is for a martin jerry mj-s01 wall switch
substitutions:
  name: "test-sw"
  on_time: 600s

esphome:
  name: ${name}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret ssid2
  password: !secret password2
  #use_address: 192.168.2.105

logger:

prometheus:

web_server:
  port: 80

api:

ota:

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: America/Chicago

switch:
  - platform: restart
    name: "${name} restart"

  - platform: gpio
    name: "${name} relay"
    pin: GPIO12
    id: relay

script:
  - id: inching
    then:
      - switch.turn_on: relay
      - output.turn_on: blue_led
      - delay: ${on_time}
      - switch.turn_off: relay
      - output.turn_off: blue_led

sensor:
  - platform: uptime
    name: ${name} uptime
    update_interval: 120s
    
  - platform: wifi_signal
    name: ${name} wifi signal
    update_interval: 120s

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    name: "${name} button"
    on_press:
      - if:
          condition:
            switch.is_on: relay
          then:
            - script.stop: inching
            - switch.turn_off: relay
            - output.turn_off: blue_led
            - output.turn_off: red_led
          else:
            - script.execute: inching
    on_click:
      - min_length: 500ms
        max_length: 2000ms
        then:
          if:
            condition:
              script.is_running: inching
            then:
              - script.stop: inching
              - output.turn_off: blue_led
              - output.turn_on: red_led
  - platform: gpio
    pin:
      number: GPIO1
      mode: INPUT_PULLUP
    name: "${name} sw2"

output:
  - platform: gpio
    id: blue_led
    pin: GPIO5
    inverted: True
    
  - platform: gpio
    id: red_led
    pin: GPIO4
    inverted: True

