substitutions:
  me: "esp32c6"

esphome:
  name: ${me}
  comment: sparkfun esp32c3
  on_boot: 
    - priority: 0
      then:
        - deep_sleep.prevent: sleeper

esp32:
  board: sparkfun_esp32c6_thing_plus
  framework:
    type: esp-idf

external_components:
  - source: github://burundiocibu/c6_adc

logger:
  level: INFO

ota:
  - platform: esphome
    password: !secret esp_ota_pw
    id: my_ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  reboot_timeout: 60s
  id: wifi_id
  manual_ip: 
    static_ip: 192.168.2.197
    gateway: 192.168.2.1
    subnet: 255.255.255.0
    dns1: 192.168.2.1

web_server:
  version: 2

deep_sleep:
  id: sleeper
  sleep_duration: 60s
  run_duration: 30s

globals:
  - id: sleep_duration
    type: long
    initial_value: "0"

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  id: mqtt_client
  discovery: true
  # Set these empty so the device is not marked missing by home assistant
  will_message:
  birth_message:
  on_json_message: 
    topic: ${me}/cmd/sleep
    then:
      - lambda: |-
          unsigned duration = 60;
          if (x.containsKey("duration"))
            duration = long(x["duration"]);
          if (duration > 0)
          {
            unsigned sd = duration*1000 - millis();
            sd = min(duration*1000, sd);
            ESP_LOGI("sleeping", "millis:%d, duration:%d", millis(), sd);
            id(sleeper).set_sleep_duration(sd);
            id(sleeper).begin_sleep(true);
          }

i2c:
  sda: GPIO5
  scl: GPIO6

one_wire:
  - platform: gpio
    pin: GPIO9

sensor:
  - platform: internal_temperature
    name: ${me} internal temperature
    id: temp
    update_interval: 250ms
    unit_of_measurement: °C
    filters:
      - sliding_window_moving_average:
          window_size: 10
          send_every: 10
          send_first_at: 10

  - platform: c6_adc
    pin: GPIO1
    name: ${me} vbat
    id: vbat
    attenuation: 12db # full scale is 2.450V
    accuracy_decimals: 2
    update_interval: 250ms
    filters:
      - multiply: 2
      - sliding_window_moving_average:
          window_size: 10
          send_every: 10
          send_first_at: 10


  - platform: dallas_temp
    name: t1
    # sensor by pressure sensor
    address: 0x33011877a466ff28
    update_interval: 10s
  - platform: dallas_temp
    name: t2
    # by water
    address: 0xe9011877b40fff28
    update_interval: 10s
  - platform: honeywellabp2_i2c
    address: 0x28
    pressure:
      name: pressure
      id: p
      min_pressure: -60
      max_pressure: 60
      transfer_function: "A"
      unit_of_measurement: mBar
      accuracy_decimals: 3
  - platform: template
    lambda: "return id(p).state;"
    name: level
    update_interval: 10s
    unit_of_measurement: cm
    filters: 
      - multiply: 1.0197

