# This is for a sonoff IW101 1 gang wall switch
substitutions:
  name: "lounge-flood-lights"
  on_time: 2700s

esphome:
  name: ${name}
  platform: ESP8266
  board: esp8285
#  includes:
#    - custom/gosund_sw2_light.hpp
#    - custom/gosund_sw2_light.cpp

wifi:
  ssid: !secret ssid2
  password: !secret password2
#  use_address: 192.168.2.119

logger:
  level: verbose
  baud_rate: 0 # dimmer uses serial

prometheus:

web_server:
  port: 80

api:

ota:

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: America/Chicago

switch:
  - platform: restart
    name: "${name} restart"
    id: lounge_flood_lights_restart

sensor:
  - platform: uptime
    name: ${name} uptime
    update_interval: 120s
    
  - platform: wifi_signal
    name: ${name} wifi signal
    update_interval: 120s

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: True
    name: "${name} button"
    on_press:
      - light.toggle: lounge_flood_lights
    on_click:
      min_length: 5s
      max_length: 10s
      then:
        - switch.turn_on: lounge_flood_lights_restart

output:
  - platform: gpio
    id: led1
    pin: GPIO13
    inverted: True
    
  - id: white_led
    platform: gpio
    pin: GPIO12
    inverted: true

tuya:

light:
  - platform: binary
    id: red_led
    name: Red Led
    output: led1
    
  - platform: tuya
    name: lounge_flood_lights
    id: lounge_flood_lights
    dimmer_datapoint: 2
    switch_datapoint: 1
    min_value: 0
    max_value: 100

#  - platform: custom
#    lambda: |-
#      auto light_out = new gosund::GosundLight(id(white_led));
#      App.register_component(light_out);
#      return {light_out};
#    lights:
#      - name: ${name}
#        id: loung_flood_lights
#        gamma_correct: 1.0
#        default_transition_length: 0s

uart:
  id: uart_bus
  baud_rate: 9600
  tx_pin: GPIO1
  rx_pin: GPIO3
  

