# This is for a treatlife DS02 three way wall dimmer switch
# 
substitutions:
  name: "lounge-wall-lights"
  on_time: 2700s

esphome:
  name: ${name}
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret ssid2
  password: !secret password2
#  use_address: 192.168.2.119

logger:
  level: debug
  baud_rate: 0 # dimmer uses serial

prometheus:

web_server:
  port: 80

api:

ota:

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: America/Chicago

switch:
  - platform: restart
    name: "${name} restart"

sensor:
  - platform: uptime
    name: ${name} uptime
    update_interval: 120s
    
  - platform: wifi_signal
    name: ${name} wifi signal
    update_interval: 120s

tuya:

light:
  - platform: tuya
    name: ${name}
    dimmer_datapoint: 2
    switch_datapoint: 1
    min_value_datapoint: 3     #guessing
    min_value: 100
    max_value: 1000

uart:
  id: uart_bus
  baud_rate: 115200
  tx_pin: GPIO1
  rx_pin: GPIO3
  

