# wemos d1 mini w oled 0.66 shield (SSD1306 driver on I2C 0x3c)
# 64x48 pixels across
# i2c buttons at i2c 0x31
# NAU7802 on I2C at 0x2a
substitutions:
  me: biltong-scale

esphome:
  name: ${me}
  comment: wemos d1-mini

esp8266:
  board: d1_mini
    
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: debug

api:
  encryption:
    key: !secret esp_api_key

ota:
  password: !secret esp_ota_pw
  id: my_ota

prometheus:

web_server:

external_components:
  - source:
      type: local
      path: components

time:
  - platform: homeassistant
    timezone: America/Chicago

text_sensor:
  - platform: version
    name: ${me} ESPHome Version

switch:
  - platform: restart
    name: ${me} restart

i2c:
  sda: D2
  scl: D1
  frequency: 200kHz

sensor:
  - platform: uptime
    name: ${me} uptime
    update_interval: 120s

  - platform: wifi_signal
    name: ${me} wifi signal
    update_interval: 120s

  - platform: nau7802
    address: 0x2a
    gain: 128
    voltage:
      name: vb
    update_interval: 1s

font:
  - file: "gfonts://Ubuntu\ Mono"
    id: f1
    size: 12

display:
  - platform: ssd1306_i2c
    model: "SSD1306 64x48"
    address: 0x3c
    lambda: |-
      it.print(0,0,id(f1), "Hello");
      it.print(0,12,id(f1), "World");
