# Hardware is a Shelly EM
# ADE7952 at 0x38 on I2C
# PCF8563 at 0x51 on I2C
# Relay on GPIO15
# LED on GPIO2 (another site says GPIO0)
# See here for example of lambda to calibrate: https://community.home-assistant.io/t/anyone-using-shelly-em/149867/6
# basic sensor on esphome here: https://esphome.io/components/sensor/ade7953.html
# for an arduino sketch: https://github.com/apreb/shellyEMmockup/blob/master/src/shellyEMmockup.ino
substitutions:
  name: house-panel

esphome:
  name: ${name}
  platform: ESP8266
  board: esp8285
  comment: "Shelly EM"

wifi:
  ssid: !secret ssid2
  password: !secret password2
#  use_address: 192.168.2.245

# Enable logging
logger:
  level: info

# Enable various APIs
api:

ota:

prometheus:

web_server:
  port: 80

switch:
  - platform: restart
    name: ${name} restart

time:
  - platform: sntp
    id: sntp_time
    timezone: America/Chicago

i2c:
  sda: GPIO12
  scl: GPIO14

status_led:
  pin:
    number: GPIO0
    inverted: yes

sensor:
  - platform: wifi_signal
    name: ${name} wifi signal
    update_interval: 120s

  - platform: ade7953
    irq_pin: GPIO16
    voltage:
      name: ${name} voltage
    current_a:
      name: ${name} current p2
    current_b:
      name: ${name} current p1
    active_power_a:
      name: ${name} active power p2
      id: active_power_p2
      internal: true
    active_power_b:
      name: ${name} active power p1
      id: active_power_p1
      filters:
        - multiply: -1 # yea, don't ask, and no, the other channel doesn't need it
      internal: true
    update_interval: 5s

  - platform: template
    name: house power
    id: house_power
    lambda: return -(id(active_power_p1).state + id(active_power_p2).state);
    unit_of_measurement: W
    icon: "mdi:flash-circle"
    update_interval: 5s

  - platform: total_daily_energy
    name: house daily energy
    power_id: house_power
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh

binary_sensor:
  - platform: gpio
    pin: GPIO16
    name: "ade7953 IRQ pin"
    internal: true

output:
  - platform: gpio
    pin: GPIO15
    id: house_panel_relay
