# This is for a sonoff basic switch module
substitutions:
  name: "north-fairies"

esphome:
  name: ${name}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret ssid2
  password: !secret password2
  use_address: 192.168.2.230

prometheus:

web_server:
  port: 80

logger:

api:

ota:

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: America/Chicago


text_sensor:
  - platform: version
    name: "ESPHome Version"


switch:
  - platform: restart
    name: "${name} restart"

sensor:
  - platform: uptime
    name: ${name} uptime
    update_interval: 120s
    
  - platform: wifi_signal
    name: ${name} wifi signal
    update_interval: 120s
    
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${name} button"
    on_press:
      - light.toggle: north_fairies

light:
  - platform: binary
    name: North Fairies
    id: north_fairies
    output: relay
    
output:
  - platform: gpio
    pin: GPIO12
    id: relay
  
status_led:
  pin: GPIO13

